# Generated by Django 4.1.1 on 2022-10-03 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_item_listitem_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.item'),
        ),
    ]
