# Generated by Django 4.1.1 on 2022-10-03 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_listitem_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='listitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.listitem'),
        ),
    ]
