# Generated by Django 4.1.1 on 2022-10-04 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_listitem_items_item_listitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='listitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_items_list', to='base.listitem'),
        ),
    ]
