# Generated by Django 4.1.1 on 2022-10-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_serre_kult_serre_pers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serre',
            old_name='kult',
            new_name='culture',
        ),
        migrations.RenameField(
            model_name='serre',
            old_name='pers',
            new_name='person',
        ),
        migrations.AlterField(
            model_name='serre',
            name='dataSerre',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='serre',
            name='sysSerre',
            field=models.JSONField(default=dict),
        ),
    ]
