# Generated by Django 4.1.1 on 2022-10-07 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_kult_serre_culture_rename_pers_serre_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='intitule',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='firebaseId',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serre',
            name='culture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serrekult', to='base.culture'),
        ),
        migrations.AlterField(
            model_name='serre',
            name='dataSerre',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='serre',
            name='hashSerre',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='serre',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serrepers', to='base.person'),
        ),
        migrations.AlterField(
            model_name='serre',
            name='sysSerre',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
