# Generated by Django 4.1.1 on 2022-10-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_culture_intitule_alter_person_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serre',
            name='kultSerre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
